### PR TITLE
Breakup GPIOBUS

### PR DESCRIPTION
**Pull request by akuker**
This is intended to separate the systimer class from gpiobus and to move the different board types to their own header files. There shouldn't be any functional changes.

I removed the -Wextra from the Makefile since it looks like we lost that change. Let me know if you think it needs to stay in there.

### CODE REVIEW

**Comment by akuker** [comment]
Note: there are other changes/improvements needed. This is just the initial PR to break things up. More changes will be coming

**Comment by uweseimet** [comment]
@akuker Not sure what you mean with -Wextra. Currently it is part of the build process (this is why I found the compile-time issue on buster today), and it should stay in the Makefile, because our code compiles fine with it.

**Review by uweseimet — APPROVED** [review]
Approved, from my side. Please check my comment on -Wextra, please.

**Comment by akuker** [comment]
> Approved, from my side. Please check my comment on -Wextra, please.

I added this back in. Thanks @uweseimet !

**Comment by akuker** [comment]
[0cb6948](https://github.com/akuker/RASCSI/pull/843/commits/0cb694846defd08f295f1f6e310b8b19add1da92) and [42178fb](https://github.com/akuker/RASCSI/pull/843/commits/42178fb822e1260458aa16725ea35b09068290ab) are identical now. 

@uweseimet - would you mind taking a look at this again and make sure I didn't mess something up? I accidentally checked in a bunch of banana pi changes before I merged this PR :(

**Comment by uweseimet** [comment]
@akuker I could not find anything obviously wrong. I don't think that anything bad can happen anyway, because essentially that is a code move and not a change, and I bet that if something was wrong, rascsi would not work at al anymorel, i.e. there is hardly any potential of missing anything hidden.

**Comment by akuker** [comment]
Thanks @uweseimet

**Pull request merged**
