### PR TITLE
In case all IDs are reserved recommend 0

### PR DESCRIPTION
**Pull request by philenotfound**
Otherwise the occupied list is empty and this exception brings down the
whole web interface.

This can be easily provoked by just reserving all IDs in the web interface.

### CODE REVIEW

**Comment by rdmark** [comment]
@philenotfound Thanks for taking the time to submit a patch! Now, are you sure you tested this against the master branch code? I can honestly not reproduce the reported issue.

**Review by rdmark — CHANGES_REQUESTED** [review]
Cannot reproduce issue that this code supposedly fixes.

**Comment by philenotfound** [comment]
Reproduced with 348b5dd026804f4abab99d44808a94e79e82838b.

1. Detach All Devices.
2. Click Reserve on every device. Reserving the last one will crash the web app.

```
Jul 01 06:24:56 rascsi RASCSIWEB[977]: [2022-07-01 06:24:56,262] ERROR in app: Exception on / [GET]
Jul 01 06:24:56 rascsi RASCSIWEB[977]: Traceback (most recent call last):
Jul 01 06:24:56 rascsi RASCSIWEB[977]:   File "/home/pi/RASCSI/python/web/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
Jul 01 06:24:56 rascsi RASCSIWEB[977]:     response = self.full_dispatch_request()
Jul 01 06:24:56 rascsi RASCSIWEB[977]:   File "/home/pi/RASCSI/python/web/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
Jul 01 06:24:56 rascsi RASCSIWEB[977]:     rv = self.handle_user_exception(e)
Jul 01 06:24:56 rascsi RASCSIWEB[977]:   File "/home/pi/RASCSI/python/web/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
Jul 01 06:24:56 rascsi RASCSIWEB[977]:     rv = self.dispatch_request()
Jul 01 06:24:56 rascsi RASCSIWEB[977]:   File "/home/pi/RASCSI/python/web/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
Jul 01 06:24:56 rascsi RASCSIWEB[977]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jul 01 06:24:56 rascsi RASCSIWEB[977]:   File "/home/pi/RASCSI/python/web/src/web.py", line 132, in index
Jul 01 06:24:56 rascsi RASCSIWEB[977]:     scsi_ids, recommended_id = get_valid_scsi_ids(devices["device_list"], reserved_scsi_ids)
Jul 01 06:24:56 rascsi RASCSIWEB[977]:   File "/home/pi/RASCSI/python/web/src/web_utils.py", line 35, in get_valid_scsi_ids
Jul 01 06:24:56 rascsi RASCSIWEB[977]:     recommended_id = occupied_ids.pop(0)
Jul 01 06:24:56 rascsi RASCSIWEB[977]: IndexError: pop from empty list
```

To recover you have to restart rascsi-web.service

**Comment by rdmark** [comment]
Now I get it, thanks. Somehow I read it as *attaching* to all ids. It is quite the corner case. Good catch!

**Review by rdmark — APPROVED** [review]

**Comment by rdmark** [comment]
One request for future contributions: Please prepare PRs against the develop branch. We never work directly in the master branch.

**Pull request merged**
