### PR TITLE
Host services (SCHS) with realtime clock and shutdown, improved device inheritance

### PR DESCRIPTION
**Pull request by uweseimet**
This PR covers the RaSCSI host services device with both realtime clock and RaSCSI/Pi shutdown. Successfully tested with an Atari.

This PR also improves inheritance and moves code from the Disk class to a new base class, which makes implementing new non-disk device types much easier and less prone to side effects. Just subclassing PrimaryDevice without implementing anything already results in a valid SCSI device with working implementations of TEST UNIT READY, INQUIRY, REQUEST SENSE and REPORT LUNS. Any device-specific code can simply be added to the subclass.

### CODE REVIEW

**Comment by akuker** [comment]
@uweseimet  - I have some hesitation in calling this device a "RaSCSI" device. I think it could add confusion to add a RaSCSI device to the RaSCSI service. Do you have any ideas for a different name for this? If we didn't already have a "host bridge" that would be a decent name. Or, should we add this functionality to the host bridge?

**Comment by uweseimet** [comment]
@akuker The host bridge has well-defined functionality of its own. We should not mix it with anything else.
I'm not sure what you mean with your note on the RaSCSI device. All devices we have use "RaSCSI" as the vendor string. This device has "Service Device" as its product name, so that's the device name. Do you mean the term "device" should not be part of the product name? In this case we might call it "Service Channel". "Service Interface" might qualify, but it's one character too much.

**Comment by akuker** [comment]
> @akuker The host bridge has well-defined functionality of its own. We should not mix it with anything else. And there is one more issue: The bridge modifies your network settings, I'm not sure what you mean with your note on the RaSCSI device. All devices we have use "RaSCSI" as the vendor string. This device has "Service Device" as its product name, so that's the device name. Do you mean the term "device" should not be part of the product name? In this case we might call it "Service Channel". "Service Interface" might qualify, but it's one character too much. "Host Services" may be even better, with the device type being "SCHS".

In the man pages, its called "rascsi: RaSCSI control device". Also, the filename is scsi_rascsi.cpp. I'm fine with "Service Device", "Service Channel" or "Host Services" (and changing the device type to something other than SCRA). 

Are you OK with removing the "RaSCSI" nomenclature from references to this new device?

**Comment by uweseimet** [comment]
@akuker Let's use "Host Services". I will update everything accordingly. What's still not clear to me is what you mean with "RaSCSI" nomenclature. The only "RaSCSI" string that would remain is "RaSCSI" as the INQUIRY vendor name. This is IMHO correct, because "RaSCSI" is the vendor for all device types supported, i.e. also for the "Host Services" device type.

**Comment by uweseimet** [comment]
@akuker Any chance for more feedback (based on my changes)? This open PR is currently preventing me from trying to address other tickets, in particular https://github.com/akuker/RASCSI/issues/660, https://github.com/akuker/RASCSI/issues/189, https://github.com/akuker/RASCSI/issues/222 and https://github.com/akuker/RASCSI/issues/179. I don't know how far I may be able to get with these, but this PR would have to be merged first.

**Comment by akuker** [comment]
> @akuker Any chance for more feedback (based on my changes)? This open PR is currently preventing me from trying to address other tickets, in particular #660, #189, #222, #185 and #179. I don't know how far I may be able to get with those, but this PR would have to be merged first.

Done! Sorry for the delay.

**Comment by uweseimet** [comment]
@akuker Thank you for merging. You may have seen that I continued working on this, and I'm quite satisfied with the progress. I guess it will take one more PR to finalize the structural improvements, but this PR will very have less code changes.

**Pull request merged**
