### PR TITLE
User authentication in the Web Interface

### PR DESCRIPTION
**Pull request by rdmark**
- Introduce login endpoint that authenticates with Linux users in the sudo group using the simplepam library
- Introduce logout endpoint that removes the authenticated user from the session
- Add a login form to the header of the base page (instead of the now-useless "service active" banner), and a logout link for when logged in
- Stops execution of potentially destructive endpoints unless a user is actively authenticated
- Open links to github in new tabs (since there's a heightened risk for misclicking now)

### CODE REVIEW

**Comment by akuker** [comment]
@rdmark - I think we should make this feature optional before we merge it into develop. The feature should probably default to `off` as well (at least for now)

**Comment by rdmark** [comment]
> @rdmark - I think we should make this feature optional before we merge it into develop. The feature should probably default to `off` as well (at least for now)

As per your suggestion in a different thread, the code now checks for the existence of a 'rascsi' group and enables authentication only if found. Then it allows logging in only by users in aforementioned group.

**Review by akuker — APPROVED** [review]

**Comment by akuker** [comment]
This feature is awesome!!! Thank you @rdmark !!!

**Comment by rdmark** [comment]
@akuker My pleasure! Thanks for trying it out.

**Pull request merged**
