### PR TITLE
Feature extended server information

### PR DESCRIPTION
**Pull request by uweseimet**
Notes on additional changes, resulting from issues I stumbled upon when working on this PR:

- Replaced BOOL by bool for fields that are definitely booleans and not integers.
- The PROTECT command is not toggling anymore but always protects. UNPROTECT always unprotects.
- Robustness: Moved sanity checks from rasctl to rascsi, so that these checks are run for any client and cannot be circumvented.
- rascsi does not mention "rasctl" in its error messages anymore, because there may be other clients
- Open() now returns an error string, so that error messages can be more concise
- The supports_file attribute of PbDevice indicates whether the device supports an image file. BR and DAYNAPORT don't.

### CODE REVIEW

**Comment by akuker** [comment]
I couldn't get this to compile. 

The first change needed is to add `#include <sys/mman.h>` to the top of gpiobus.cpp (since you removed it from os.h.... it really should have been in gpiobus.cpp to begin with).

Then, on line 229 of rasctl.cpp, 'type' needs to be initialized to something.

**Comment by uweseimet** [comment]
@akuker I tested the compilation on my Pi by copying the files to the Pi from my main development machine. But I must have missed something (probably copied the files to the wrong location), because with the checked out sources I also have issues.
I'm sorry for that, I'm going to fix this now.

**Comment by uweseimet** [comment]
@akuker Regarding linke 229, no initialization is required. It's a documented feature of protobuf that enums are initialized by default with the first enum value
I just aded the missing include, and now everything compiles on my Pi.

**Comment by uweseimet** [comment]
@akuker I did a lot of drive attribute testing (removable, read-only etc.). As a subject for discussion we should decide whether hard disk drives should be write-protectable in general. With the code of this PR this is the case. Reasons why they should be:

- This is convenient for the user. One can protect hard disk images that should not be modified without dealing with file permissions.
- There are non-MO drives that can be write protected, like ZIP or JAZ. Usually a proprietary SCSI command is used for that, but there is not much software that knows how to use these proprietary commands. So instead of emulating a ZIP or JAZ device just to have non-MO drives with write protection, having the means to protect a hard disk in general is a more flexible approach.

**Review by akuker — APPROVED** [review]

**Comment by uweseimet** [comment]
@akuker Can you please tell me which compiler version caused the compile-time error? As already mentioned I don't get any compiler error on my Pi.

**Comment by akuker** [comment]
> @akuker I did a lot of drive attribute testing (removable, read-only etc.). As a subject for discussion we should decide whether hard disk drives should be write-protectable in general. With the code of this PR this is the case. Reasons why they should be:

No objections from me. I can definitely understand the use case where you want to make a HD read-only. 

Note: I still got the compiler error about type being uninitialized in rasctl, so I just added the initialization of it.

**Pull request merged**
