### PR TITLE
Add Daynaport SCSI/Link Functionality

### PR DESCRIPTION
**Pull request by akuker**
Added the ability to emulate the DaynaPort SCSI/Link device to RaSCSI.
Before using you will want to run "setup_bridge.sh" so that the emulated DaynaPort will have something to connect to.
Also added more useful logging to rascsi.cpp. It should log something whenever a user add/removes/reconfigures a device.

### CODE REVIEW

**Comment by akuker** [comment]
Note: This pull request is for Issue #27

**Review by TomRBarber — APPROVED** [review]
A+ work

**Review by TomRBarber — APPROVED** [review]
A++ Work

**Review by TomRBarber — APPROVED** [review]
Super A+ Work!

**Pull request merged**
