### PR TITLE
Pushes to develop trigger all GHA workflows

### PR DESCRIPTION
**Pull request by nucleogenic**
Update to GHA triggers such that:

* PR merges triggers all workflows
* Direct pushes to develop triggers all workflows

Todo:

- [x] Test on forked repository

### CODE REVIEW

**Comment by nucleogenic** [comment]
Tested on my fork and seems to work as expected, so bringing this PR out of draft.

https://github.com/nucleogenic/RASCSI/actions?query=branch%3Adevelop+event%3Apush

**Comment by uweseimet** [comment]
@nucleogenic There is still something wrong: Changes in branches do not trigger any action anymore. Without a PR nothing is built, no unit tests are run.

**Comment by nucleogenic** [comment]
Hi @uweseimet, this is by design, as we can raise a draft PR when we want feedback from CI.

This prevents annoying and premature CI failure emails (and wasting build minutes, although they are free here).

We can revert to the previous behaviour for the C++ workflows if you like? For Python it's actually much quicker to run the tools and get feedback locally.

**Comment by uweseimet** [comment]
@nucleogenic I would very much appreciate having the previous behavior for C++ back. I need branches without PRs to test things before I raise a PR. IMO forcing a PR for feedback from CI is a disadvantage, because everybody involved in this (draft) PR constantly gets e-mails with build messages. PRs should be raised when the respective funtionalitiy is available, because they deal with reviewing, not about reflecting any intermediate commit. I have already been a victim of these emails, which is not nice. I tend to avoid commenting on PRs now, because otherwise I get spam emails all the time.
Just like you I also don't like wasting build minutes, but I don't think GitHub provides any alternative.

**Comment by uweseimet** [comment]
@nucleogenic One more thing: I noticed that recently there were PRs with a huge number of comments and changes. We never had such long-running PRs before. This is probably a result of your changes. But when you create PRs this early you get builds for each commit just as before, don't you? All in all this does not save any build minutes. But it increased the amount of spam emails sent.

**Comment by nucleogenic** [comment]
@uweseimet 

> I would very much appreciate having the previous behavior for C++ back. I need branches without PRs to test things and to see the SonarCloud results before I raise a PR. 

Please see PR #1003

> But when you create PRs this early you get builds for each commit just as before, don't you? All in all this does not save any build minutes.

I usually commit and push quite frequently due to working on two computers, but I will squash the commits if uninteresting to reviewers (e.g. anything like 'WIP - unit of work X') before the PR is raised, so it might not be obvious, but I would expect to see a reduction for my use case. Of course, it depends on the change set, how early feedback is needed from others, and how much change that feedback drives. Some changes like web UI theme and GHA changes are more opinionated, so attract a greater volume of feedback and changes.

In any case, these things are not set in stone and I am happy to revert changes that don't work out.

**Comment by uweseimet** [comment]
@nucleogenic At least from my perspective it would also be fine to just run the code analysis workflow on a push. Building everything is implicit for this workflow, i.e. the explicit build step does not provide much more insight than only running the analysis workflow.

**Pull request merged**
