### PR TITLE
Feature image padding

### PR DESCRIPTION
**Pull request by rdmark**
Web UI for padding HD and CD images up to the nearest multiple of 512 and 2048 bytes, respectively. I think these two will cover the most common usecases. It also allows you to pad MO images up to the nearest valid file size.

### CODE REVIEW

**Comment by akuker** [comment]
@rdmark - could I ask you to resolve the conflicts with develop?

**Comment by rdmark** [comment]
@akuker Yes sure, give me a min.

**Comment by rdmark** [comment]
@akuker It should work now, but I'm seeing parts of the 'show properties' PR as well so let me know if something got messed up somehow....

**Comment by rdmark** [comment]
Alright to the obvious reason the 'show properties' code is in this PR, is because https://github.com/akuker/RASCSI/pull/270 was accidentally merged here instead of develop...

**Review by akuker — APPROVED** [review]

**Pull request merged**
