### PR TITLE
Ported the monitor to python 3

### PR DESCRIPTION
**Pull request by gbin**

### CODE REVIEW

**Comment by erichelgeson** [comment]
Thanks for the contribution, though this was already one in https://github.com/akuker/RASCSI/pull/83

**Comment by gbin** [comment]
ok FP :)

**Comment by gbin** [comment]
but wait on master this is still some py2 code

**Comment by gbin** [comment]
The master branch should always reflect the contents of the last stable release
:( ok FP#2 :)

**Comment by gbin** [comment]
Maybe change the default branch to develop?

**Comment by erichelgeson** [comment]
Master is the latest stable release - and yes we should change the default branch.

**Pull request closed without merging**
