### PR TITLE
Use Netatalk 2.x v220101

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Comment by bzeiss** [comment]
@rdmark I don't have an old Mac (or any Mac actually), so I suspect I have no proper way to test this completely. But I have tried to compile the branch and it exited with a zeroconf installation not found error. 

image

I'm suspecting that an apt install libavahi-client-dev is missing somewhere in easyinstall.sh. Other than that, I can only say that it it compiles and papd+timelord are running on my pi4 ;-) So I'm not sure whether it makes sense for me to approve the old mac specific pull requests. I can basically only compile and dry-look at the code.

**Comment by rdmark** [comment]
@bzeiss That's a good catch! For some reason, I was assuming that libcups-dev pulls in libavahi-client-dev, which seems to have been incorrect. I updated the list of packages to install now!

Did you see the _atalkd_, _cnid_ and _afpd_ daemons get installed and run as well? These three are the core file sharing enabling services.

**Comment by bzeiss** [comment]
@rdmark Ah, yes, atalkd, cnid_metad and afpd are running. I wasn't aware that these are installed as well. I was just looking at the services mentioned in the install script.

**Comment by rdmark** [comment]
@bzeiss Good point. I've added a systemctl status command to make it clear which services have been added.

**Comment by rdmark** [comment]
Converting to draft to add a few more steps to automate papd configuration (CUPS)

**Comment by rdmark** [comment]
The script will now install and configure CUPS as well, which should make the printer server work out of the box with most CUPS compatible printers.

**Review by akuker — APPROVED** [review]

**Pull request merged**
