### PR TITLE
DaynaPort: Ignore commands with a bogus control value

### PR DESCRIPTION
**Pull request by jcs**
All traffic from the DaynaPort will have a control value of 0xc0 or
0x80, so any commands that don't should be ignored.

This helps the Mac Plus which will try to READ(6) from the DaynaPort
device if it's attached at boot and then try to interpret the
ethernet packet as hard drive data and crash.

See issue akuker#419

### CODE REVIEW

**Comment by uweseimet** [comment]
@jcs Just looking at your PR. I think we misunderstood, or I misunderstood. I thought there was a way to report NOT_READY without looking at the CDB, because we cannot really know (because it is not documented) whether the last bytes definitely have to be 0x80 or 0xc0.

Can you also fix the cast issue, i.e

```
scsi_cmd_read_6_t *command = (scsi_cmd_read_6_t*)cdb;
```

**Comment by jcs** [comment]
I opened the cast fix as a separate PR.

I'm not sure how else to check for valid DaynaPort requests without looking at that control field in the CDB.  I did try `SetStatusCode(STATUS_INVALIDCDB)` instead but it still crashes the Mac Plus.

**Comment by uweseimet** [comment]
@jcs I see. I thought you had found a way to detect whether the Daynaport has not been initialized, so that we would not have to look at the CDB.
In case we have to look at the CDB, please try whether your Mac is also fine when your report INVALID_FIELD_IN_CDB instead of NOT_READY. When we make a decision based on CDB contents NOT_READY would not be a valid response.

**Review by uweseimet — APPROVED** [review]

**Review by uweseimet — APPROVED** [review]

**Comment by uweseimet** [comment]
@jcs Please note that your patch has to be created against the develop branch, not the master branch. This is why we cannot merge.

**Comment by jcs** [comment]
I tried `SetStatusCode` but not returning `controller->Error(ERROR_CODES::sense_key::NOT_READY, ERROR_CODES::asc::NO_ADDITIONAL_SENSE_INFORMATION)`.  That does seem to boot and work properly so I'll switch to that.

**Review by uweseimet — APPROVED** [review]

**Comment by uweseimet** [comment]
@jcs I just rebased to develop and merged.

**Pull request merged**
