### PR TITLE
Image file operations with nested folders, folder filter

### PR DESCRIPTION
**Pull request by uweseimet**

### CODE REVIEW

**Comment by uweseimet** [comment]
@bzeiss You are explicitly invited to help with testing these changes, because your ticket triggered these changes ;-). You do not even need special (synthesizer) hardware for testing.

**Comment by bzeiss** [comment]
Doing some tests with this branch in the next few hours...

**Comment by bzeiss** [comment]
@uweseimet First tests worked well (writing/reading on nested disks). One question though: the (I think really nice) feature is disabled by default. For backwards compatibility, I can understand that the defensive way is to keep the search depth at -R 0, but does it really matter? From what I see, the name is preserved when the file is located in the ~/pi/images root folder and for nested images, the path is prefixed in the image list. So there is no risk of a name overlap. The configuration save option (~/.config/rascsi/xxx.json) always saves the full path it seems. So there is no risk for ambiguity here either from what I see. So in the worst case, someone who has images already located in nested folders will have the missing images magically appear in the list. In my opinon, this is the desired behavior. 

I have done a quick test where I placed a hds file with the same name in ~/images and one in ~/images/disks. In the default.json, I have saved the ~/images hds file when rascsi was executed with -R 0. I have then switched rascsi to -R 5 and restarted rascsi-web. With that change, I have two hds files with the same name, but in different folders. After that, rascsi-web still loaded the correct image because it referenced the whole path. So I would say the change is backward compatible anyway and it should be save to set something like -R 4 or -R 5 as the default value.

There is one actual problem I have found in rascsi-web. When I mount an image in a nested folder in rascsi-web, the attached image isn't shown as attached in the "image file management" list, but it is listed as if nothing happend and I can still select it for attachment, renaming and deletion. However, it is properly attached in rasctl and it is listed in the SCSI ID mapping table in rascsi-web, so it generally works as expected despite the bug. This is true for any image in a nested folder. If I attach the image with the same name in ~/images and ~/images/disks from its nested folder in ~/images/disks, then the image in ~/images is shown as attached despite the fact that it isn't (but the nested sibiling with the same name). I hope this makes sense.

**Comment by uweseimet** [comment]
@bzeiss Thank you for testing.
I cannot comment on how the web ui behaves with nested folders, because I never use it ;-). I either use rasctl or my app, and those two I also use for testing. @rdmark should comment on whether the default should be -R 1 or even deeper (even though I would recommend not making the default too deep) instead of -R 0. I assume that @rdmark is also going to have a look at the issue in the web ui you found.

**Comment by bzeiss** [comment]
@rdmark @uweseimet For what it's worth: renaming and deleting nested images (depth=1) through rascsi-web worked for me.

**Comment by uweseimet** [comment]
@rdmark Did you also test renaming etc. with deeper structures, e.g. "a/b/c.iso" to "w/x/y/z.iso", which will move the file to a new location? There are quite a lot of scenarios that are completely new.

**Comment by bzeiss** [comment]
@uweseimet no, just depth=1, but I can try a few more things with more nesting. No problem.

**Comment by uweseimet** [comment]
@bzeiss Sounds good, thank you. Please try to break the new functionality.

**Comment by bzeiss** [comment]
A few results:
- create empty disk image is safe. When I enter something like "disks/a/b/foo", the slashes are then mapped to underscores. The image is placed in ~/images. This is fine I think. Ideally, the disk creation would understand the slashes and create the respective folders. But I guess that is not strictly necessary.
- When I start with -R 5 and have a file "foo/bar/foobar/test01.hds", I cannot rename it to "foo/bar/foobar/test02.hds" and rascsi complains "error] Invalid folder hierarchy depth '/home/pi/images/foo/bar/foobar/test01.hds'". I'm not sure how the depth is counted, but starting with \-R 6 doesn't work as well. It is starting to work with \-R 7. So I guess every path including the file name counts. So this is maybe something to keep in mind when setting a different default depth. In that case \-R 5 starts to sound like low number as it generally allows renaming only within one subfolder. I'm not sure how this is meant to be.
- Renaming a file to a nested folder that doesn't exist or removing folders in the hierarchy seems to work well within the depth boundary even when multiple folders are renamed.
- I tried to irritate the renaming: from foo/bar/foobar/test01.hds to abc.hds/bar1/foobar2/test02.hds. This also worked fine and that file can also still be attached. 
- I tried to irritate the renaming: foo/bar/test.hds to foo/\\\\bar/\\  test.hds. This worked fine as well.

So renaming seems pretty solid to me. 

Deleting worked on everything I have tried it on.

**Comment by uweseimet** [comment]
@bzeiss Mapped to underscores? My code does not do that, but creates the required subfolders. Maybe the web ui remaps the slashes? -R 0 means no nesting, -R one level and so on.

**Comment by bzeiss** [comment]
Hah, found something:
- rename test2.hds to \test2.hds.
- File is listed as \test2.hds in the image file management.
- Click rename again
- Filename displayed: 
image

So somehow the backslash is incorrectly interpreted. Granted, this case seems pretty rare ;-)

**Comment by uweseimet** [comment]
@bzeiss I just fixed an issue with the nesting level check. With the latest sources in the feature branch the issue with -R 6/-R 7 you mentioned should be fixed.

**Comment by uweseimet** [comment]
@bzeiss With backslashes you can encode special characters, which is not unusual. If you really want a backslash to be part of a filename "\\" will probably work.

**Comment by bzeiss** [comment]
Yes, the point is: when enter the filename that I want to rename to, the escapes are ignored and the backslashes are written in the filename. However, if there are backslashes already in the filename, the characters seem to be escaped when the rename dialog is opened new in rascsi-web. This is inconsistent behavior in my opinion.

**Comment by uweseimet** [comment]
@bzeiss In case it turns out that any remaining issues are related to the web ui @rdmark might decide to merge this PR, because it is related to the C++ core only. The problem I currently have is that there are several open C++ PRs and I cannot easily run a local rascsi version that contains all changes from all these PRs ;-).

**Comment by bzeiss** [comment]
@uweseimet The rename depth change looks good to me. /home/pi/images as well as the filename are not longer counted.

**Comment by rdmark** [comment]
@bzeiss Thanks for the thorough testing. Once all the open PRs have been merged, I will go through the webapp code and make sure it accommodates nested image dirs, while addressing the bugs found here.

With regards to converting slashes to underscores: this is done by the [werkzeug.utils.secure_filename ](https://werkzeug.palletsprojects.com/en/2.0.x/utils/#werkzeug.utils.secure_filename) method in the webapp code for when creating new drive images, named drive images, and uploading files to the Pi, specifically. However, I can see how this would be unexpected for file names input by humans, so I will remove the general secure_filename conversion in create_file() and just keep the ones in named drive image and file uploads.

I don't have a strong opinion about which dir scan depth should be the default. @akuker do you want to weigh in here?

**Comment by uweseimet** [comment]
Replaced by new, consolidated PR due to merge issues.

**Pull request closed without merging**
