### PR TITLE
Feature explicit device type (rascsi)

### PR DESCRIPTION
**Pull request by uweseimet**
This change allows to explicitly specify an optional device type, which overrides the type derived from the filename. It's possible to create any device this way, also a daynaport device.

```
>rascsi -f /home/us/images -ID0 :DAYNAPORT -ID3 test.hds:cd
```

The type is case-insensitive.

Result:

```
+----+----+------+-------------------------------------
| ID | UN | TYPE | DEVICE STATUS
+----+----+------+-------------------------------------
|  0 |  0 | SCDP | DaynaPort SCSI/Link
|  3 |  0 | SCCD | /home/us/images/test.hds (WRITEPROTECT)
+----+----+------+-------------------------------------
```

I removed the device file work-around I added some time ago, because an explicit device type can be used instead.

### CODE REVIEW

**Comment by uweseimet** [comment]
@akuker Does the doc/rascsi_man_page.txt file need to be checked in? Looks as if it is recreated automatically during the build.

**Comment by akuker** [comment]
> @akuker Does the doc/rascsi_man_page.txt file need to be checked in? Looks as if it is recreated automatically during the build.

I have been commiting the changes when it re-generates.

**Review by akuker — APPROVED** [review]

**Comment by akuker** [comment]
@uweseimet - I can't thank you enough for all of the pull requests! These are all great changes, and I appreciate them.

Just as a heads up - my job is getting pretty busy and I've been stressing a little bit to keep up with your pull requests. I definitely don't want to discourage you from the types of changes you're making, but would there be a way that we could batch these up more? Maybe make a uweseimet-develop branch and we just merge that into develop once or twice a week?

Thank you again for all of your awesome PRs!!!

**Comment by uweseimet** [comment]
@akuker Sure, we can do that. I guess I will create separate feature branches but will merge them into a separate uweseimet-develop branch before creating a consolidated PR for that branch. Let's just see how this works.

**Pull request merged**
