### PR TITLE
Fixed issue with protected devices/media, added IMAGE_FILE_INFO command

### PR DESCRIPTION
**Pull request by uweseimet**

### CODE REVIEW

**Comment by rdmark** [comment]
@uweseimet Can you provide some pointers on how to test this? How do you create a protected device?

**Comment by uweseimet** [comment]
@rdmark Just set the protected flag in PbDeviceDefinition. This is a documented feature in the .proto file.

**Comment by uweseimet** [comment]
@rdmark As part of this PR I also added a new IMAGE_FILE_INFO command and renamed IMAGE_FILES_INFO to DEFAULT_IMAGE_FILES_INFO.
IMAGE_FILE_INFO provides information on image files that are not located in the default folder, e.g. device files.

**Comment by rdmark** [comment]
Alright, so I tested that attaching a hard drive device with protected=True does lead to a write-protected device in RaSCSI.

**Review by rdmark — APPROVED** [review]

**Pull request merged**
