### PR TITLE
Added unit tests and convenience methods, fixed SonarCloud issues, include file cleanup

### PR DESCRIPTION
**Pull request by uweseimet**

### CODE REVIEW

**Comment by uweseimet** [comment]
@akuker Any idea when you will have time to review? If you cannot review until Friday (tomorrow) morning CEST (my time), and in case you agree, I would like to add the changes from the code_cleanup branch to this PR. They address essentially the same: Unit tests, SonarCloud issues, removing duplication, general cleanup.

**Comment by akuker** [comment]
Hi @uweseimet - I’m out of town with only my phone, so the earliest I’ll be able to take a look is Saturday (or maybe Sunday, depending on jet lag). Feel free to queue up changes however is most efficient for you

**Comment by rdmark** [comment]
@uweseimet Do you mean python and html issues reported by Sonarcloud? How can I see them?

**Comment by uweseimet** [comment]
@rdmark Just select the branch you are interested in on https://sonarcloud.io/project/overview?id=akuker_RASCSI.

**Comment by uweseimet** [comment]
@akuker After the review, I would like to merge this PR myself, because I want to clean up the final log message.

**Comment by rdmark** [comment]
@uweseimet Thanks I found the relevant report. Glancing through the Python code smells, vulnerabilities and issues, there are a handful that are worth addressing. Others are known structural issues that pylint has reported already, but are hard to do anything about (complexity, nested if statements, etc.) without major refactoring.

As for the reported html issues: we deliberately use deprecated syntax in order to support ancient web browsers, so none of those are something that we want to address. If we can suppress html syntax deprecation warning that would be great.

**Comment by uweseimet** [comment]
@rdmark Do issues like those reported for python/common/src/util/unarchiver.py require a major refactoring?

**Comment by rdmark** [comment]
@uweseimet I agree that unarchiver.py is the one module with low hanging fruit to potentially fix.
@nucleogenic Do you want to look into it, and perhaps fold changes into a new PR or your ongoing PR?

**Comment by nucleogenic** [comment]
Hi both,

I will check out the SonarCloud reports soon and raise a new PR for any changes.

The unarchiver module is going to need refactoring to allow it to be unit tested, which is something I'm keen to investigate now we've got pytest set up.

**Review by akuker — APPROVED** [review]

**Comment by akuker** [comment]
Approved. feel free to merge!

**Comment by uweseimet** [comment]
@akuker Done, thank you for reviewing!

**Pull request merged**
