### PR TITLE
Unzip zipfiles before storing to iso

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Review by uweseimet — COMMENTED** [review]
I do not know the complete process, but when creating an ISO file, aren't the files resulting from unzipping the ZIP archive just intermediate files? If this is the case instead of explicitly storing them you can pipe the unzip output directly into mkisofs. This way there are no intermediate files, which saves disk space and also means that nothing has to be explicitly deleted later.

**Comment by erichelgeson** [comment]
MacZip files can not be unziped like this - it will result in broken files without resource forks.

**Comment by uweseimet** [comment]
> MacZip files can not be unziped like this - it will result in broken files without resource forks.

I see, but whatever tool you use to extract those files, my intention was to point out that no intermediate files should be required if this tool can extract into a pipe, and the tool creating the ISO file (like mkisofs) can get its input from the pipe.
But just as I said, I don't know the details of this process, maybe my comment does not apply.

**Comment by erichelgeson** [comment]
My reply was to the PR, not to your comment. I agree pipes would be fine here to speed up the process.

**Comment by rdmark** [comment]
Yes, I was aware of the MacZip format, but had not run into enough examples in the wild (as in, zip files floating around on the modern Web) to consider this worth considering. I did a spot check of half a dozen or so zip files off of the Macintosh Garden, and did not encounter a MacZip compressed file then.

Anyhow, I'm happy to introduce either a programmatic detection of MacZip files, or a manual opt-in/opt-out in the web interface.

**Comment by rdmark** [comment]
From a technical perspective, I like the idea of piping the output of unzip to genisoimage. The one argument against this is code complexity. Right now, the logic is that if unzip is successful, remove the original zip file and create the iso file system out of the resulting files. However, if unzip fails (or if opted out, as per the MacZip conversation) we will create the iso file system using the zip file. So we would likely have to introduce a branch with two different ways to pass data to genisoimage.

As a side question: Is it good practice to explicitly delete the tmp dir that is created by this code?

**Comment by rdmark** [comment]
Crude handling of MacZip format added. Thanks for the research @erichelgeson :)

**Comment by uweseimet** [comment]
@rdmark I think you should delete the directory you created by (most likely) with mktemp (or a similar call). Reagarding piping, IMO this would just be a few additional lines of code. The OS or python do most of the work, and most likely you would not have to deal with a temporary directory at all. So all in all it might even be less code.

**Comment by rdmark** [comment]
@uweseimet The way it's coded now, is that we manually create a dir under /tmp on the file system, then populate it with files using regular system calls. No explicit cleanup is done, but rather is left up to the Linux system. This was the state of the code when I started contributing. 

I think an improvement idea would be to use the Python 'tempfile' library which has built-in garbage collection, although this would introduce the complexity of passing the file-like Python object to either the unzip shell command (if zip file) or directly to genisoimage depending on file format, and in the former case pipe the output of the unzip shell to command to another shell command with genisoimage. I'm sure it can be done but I'd need to time to figure out the logic. I suggest this is looked into in a separate enhancement ticket. :)

**Comment by uweseimet** [comment]
@rdmark Some things can be tricky, indeed. But otherwise software development would be boring, wouldn't it? ;-)

**Review by akuker — APPROVED** [review]

**Comment by rdmark** [comment]
I created https://github.com/akuker/RASCSI/issues/543 for further improvements as discussed in this thread.

**Pull request merged**
