### PR TITLE
Fix issue 750 (Daynaport problems in develop branch)

### PR DESCRIPTION
**Pull request by uweseimet**
@akuker With this fix it should be possible to release 22.04 at last.

### CODE REVIEW

**Comment by uweseimet** [comment]
@rdmark Maybe you can approve, because you are also one of the testers for this issue.

**Review by rdmark — APPROVED** [review]

**Comment by rdmark** [comment]
@uweseimet Approved. LGTM. The one thing we should test is compatibility with the Atari ST drivers, I think.

**Comment by uweseimet** [comment]
@rdmark It's unlikely that a driver fails only because it is possible to not only request 36 but also 37 bytes. But on the other hand, you never know :). @mzryz, can you please run a quick test with the fix_issue_750 on the Atari?

**Comment by uweseimet** [comment]
@mzryz Cool, thank you!

**Pull request merged**
