### PR TITLE
Small fixes for HFS formatted drive creation in easyinstall

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Comment by uweseimet** [comment]
@rdmark Looks as if there were issues with .hds instead of .hda?

**Comment by rdmark** [comment]
> @rdmark Looks as if there were issues with .hds instead of .hda?

Not an issue per se; The reasoning here is that this script creates an HFS formatted drive image and injects the LIDO disk driver, very specifically for use on the Macintosh platform. Hence, I think it's more appropriate to use the 'hda' file ending. 

This is also what we had here traditionally, however there was a period before the 21.10 release when we almost deprecated 'hda', which is when I changed the script to use 'hds'. I forgot to revert that change when we brought 'hda' back.

**Comment by uweseimet** [comment]
@rdmark Other platforms (i.e. those using .hds) would not care (i.e. not stumble upon) any drivers or other data already present on the drive. What I mean is that from a technical perspective using .hds everywhere and discarding .hda would not cause any issues for non-Mac platforms.
Of course, supporting both .hda and .hds is not a big deal, but in general we have to be careful not to keep legacy features when they are not needed.

**Comment by rdmark** [comment]
@uweseimet I believe there is the one decisive reason for keeping support in code for hda, which we discussed in https://github.com/akuker/RASCSI/issues/274 -- out-of-the box support for initializing and mounting hard drives with Apple Drive Setup.

**Comment by uweseimet** [comment]
@rdmark You are right, I completely forgot. I should have looked into the code first, before writing my comment ;-).

**Review by akuker — APPROVED** [review]

**Pull request merged**
