### PR TITLE
Calculate image sizes for the Product string using MiB/KiB units

### PR DESCRIPTION
**Pull request by rdmark**
Addresses https://github.com/akuker/RASCSI/issues/852

### CODE REVIEW

**Comment by uweseimet** [comment]
@rdmark What's the incentive for this change? I'm not necessarily oppsing it, but would like to ask why you think that using MB is better than MiB.

**Comment by rdmark** [comment]
@uweseimet As discussed in the issue ticket, this idea here is to align with what a modern Linux or Windows (etc.) OS considers a megabyte. F.e. the example in the ticket is that if you create a 104857600 byte image file, which the host Linux OS calculates as 100 megabytes, RaSCSI reports it as a 104MB image when attached.

**Comment by uweseimet** [comment]
@rdmark Wouldn't this mean that a ZIP 100 medium is reported as 105 or so nstead of 100? Same for old drives with well-known capacity. Wouldn't this be confusing?

**Comment by rdmark** [comment]
@uweseimet For the Iomega ZIP example in particular, the references that we found is that the 100MB disk capacity was 100663296 bytes which translates to 96MiB I believe, or ~100.66 MB. (Although Iomega messed with the partitioning scheme over time and had several revisions of proprietary headers that decreased the actual capacity a bit.) Anyhow, the counter argument for a proprietary format like this is that you'd likely use a custom Product string to get the drivers to recognize the storage device, so users won't see the default "SCSI HD XXX MB" Product string anyways. See attached screenshot for an illustration.

The primary usecase for when the default Product string is shown, is when a user has created a blank no-removable drive image from scratch. In these cases, I think it makes sense to use this MiB calculation for the capacity.

sizes

**Comment by uweseimet** [comment]
@rdmark Well, there are probably pros and cons for this change. One of the other reviewers should decide ;-).

**Comment by rdmark** [comment]
@uweseimet Fair enough, that's your prerogative.

BTW, do you know the motivation behind having drive size calculated in the Product string like this in the first place? It seems a bit redundant, while adding a bit of complexity to the code.

**Comment by uweseimet** [comment]
@rdmark The motivation is that a product name change during operation would violate the standard. There are removable media drives that support different media types with different capacities. Different media would result in different names, even though the drive is still the same.

**Comment by rdmark** [comment]
@uweseimet This makes sense with regards to Removable device names being static. I'm still curious why we spell out drive sizes for SCSI HD devices though. There are other ways for RaSCSI (or the host OS) to tell you how large a drive image is, so it seems unnecessary to spell it out in the Product name. Just my two cents.

**Comment by uweseimet** [comment]
@rdmark There are drivers that (e.g. when booting) report the drives found (SCSI ID, LUN and name), and it is convenient to have the (static) capacity in the default name assigned by rascsi. Otherwise, if you use the default names, all drives would have the same names, and you do not know based on the boot message if the drive assignment is correct.

**Comment by uweseimet** [comment]
@rdmark By the way, if somebody is using a tool that remembers its setup based on drive names (such tools exist) this PR is a breaking change. I don't use such a tool, so I would not be affected, though ;-).

**Comment by rdmark** [comment]
@uweseimet If this PR gets merged I'll make sure to mention this in the release notes.

**Comment by uweseimet** [comment]
@rdmark Sounds good.

**Comment by akuker** [comment]
If I'm the tie breaker, I agree with changing to MiB. I believe MiB would be more appropriate.

Could we put a link to https://en.wikipedia.org/wiki/Binary_prefix at the bottom of the page or something with an explanation? To be honest, I had to google the difference between them.

**Review by akuker — APPROVED** [review]

**Comment by rdmark** [comment]
I think users will instinctively know what it means. In 99% of cases MB is short for MiB, except for in early computer marketing lingo.

**Pull request merged**
