### PR TITLE
Added Schematic PDF file and Step 3D model

### PR DESCRIPTION
**Pull request by akuker**

### CODE REVIEW

**Comment by rdmark** [comment]
@akuker Does the pdf file have the same contents as the step file? IMHO pdf files aren't ideal for version control, and adds heft to anyone who clones the repo.

**Comment by akuker** [comment]
The PDF has the same contents as the Schematic. STEP is a 3D model of the board. Agree that adding a bunch of PDFs to the repo isn't the greatest idea. But, I think this provides value for folks who don't have KiCAD installed.

**Comment by rdmark** [comment]
@akuker Is Kicad able to render into a version control friendly format, such as svg?

Not saying that svg would be more user friendly per se, but just exploring options. :)

**Comment by akuker** [comment]
> @akuker Is Kicad able to render into a version control friendly format, such as svg?

@rdmark - not that I'm aware of. I've removed all of the PDFs from the git repo and added them to the wiki instead. Does that sound like a better solution?

**Comment by rdmark** [comment]
@akuker Sorry for being difficult! Yes, keeping the pdfs in the wiki sounds like a good idea, at least for now. If it becomes a management overhead to keep source and wiki in sync, let's revert back to the old way of doing things...

BTW, one random thought I had is to look into if there are kicad to pdf Linux tools, to create something like a pdf generation script in the repo.

**Review by rdmark — APPROVED** [review]

**Pull request merged**
