### PR TITLE
Update nginx-default.conf

### PR DESCRIPTION
**Pull request by No0ne**
enable webinterface via ipv6

### CODE REVIEW

**Comment by rdmark** [comment]
@No0ne Thanks for raising the PR. Can you help me understand the value of enabling IPv6 for a webapp that's only expected to be running in a local network? I just want to weigh the benefits with the risk that this causes trouble in some corner case IPv4 environments out there.

**Comment by No0ne** [comment]
If you run your local network with DNS64/NAT64 and without IPv4 at all the hostname of the Raspberry Pi only registers the IPv6 address via DHCPv6 in your routers DNS host list. You could use the .local zero-conf hostname which should result in an IP4LL address, but if your PC hasn't enabled IPv4 at all this doesn't work either. So enabling IPv6 in the nginx config is the only way I could access the webinterface.

**Comment by rdmark** [comment]
Thanks for describing the use case here. I've tested it in my IPv4 environment and could not see any ill effects, so let me merge this to develop.

**Review by rdmark — APPROVED** [review]

**Comment by rdmark** [comment]
@No0ne FYI this has been merged into the develop branch

**Pull request merged**
