### PR TITLE
Added support for .hd1 (SCSI-1) image files

### PR DESCRIPTION
**Pull request by uweseimet**

### CODE REVIEW

**Comment by nucleogenic** [comment]
Hi @uweseimet @rdmark 

Since this branch is in draft status, and there are other changes present, perhaps https://github.com/akuker/RASCSI/pull/828/commits/faff3c387359e917653c287b0a33ec6e08ece030 should be split out into a separate PR?

Anybody that pulls the `develop` branch will not have a fully functional web UI or know why this is the case. I have tested the fix in this commit and it works as expected, so I think this change could be integrated straight away.

**Comment by uweseimet** [comment]
@nucleogenic I agreed with @rdmark that we would not need a separate branch for that. Anybody using the develop branch may not assume that everything is correct. But if this is blocking you, just create a PR.

**Comment by uweseimet** [comment]
@nucleogenic If everything works as expected we may be able to merge this branch tomorrow. Please see https://github.com/akuker/RASCSI/issues/814 for details.

**Comment by uweseimet** [comment]
Tested and confirmed to work by @Pacjunk

**Comment by akuker** [comment]
@uweseimet - could you resolve the conflict with `develop`?

**Comment by uweseimet** [comment]
@akuker Sure, will do this soon.

**Comment by uweseimet** [comment]
@akuker I'm done with the merge.

**Review by akuker — APPROVED** [review]

**Pull request merged**
