### PR TITLE
Move C++ code into cpp/ dir

### PR DESCRIPTION
**Pull request by rdmark**
- Moved C++ code to cpp/ from src/raspberrypi
- Related updates to Makefile, easyinstall.sh, and the github build rules
- Removed the native X68k C code in src/x68k from the repo (code has not been compiled for years and testing suggests that it's no longer compatible with RaSCSI reloaded)

### CODE REVIEW

**Comment by uweseimet** [comment]
@rdmark Looks fine for me, but surprisingly on my machine a unit test fails, which does not fail with the develop branch:
```
[ RUN      ] RascsiImageTest.DeleteImage
rascsi_test: ./devices/storage_device.cpp:64: void StorageDevice::ReserveFile(const std::string &, int, int) const: Assertion `reserved_files.find(file) == reserved_files.end()' failed.
make: *** [Makefile:174: test] Aborted
```
Your changes are based on develop, aren't they?

**Comment by rdmark** [comment]
@uweseimet Yes, this branch is based on the latest develop. It's odd that a UT would fail for you, I agree. There must be some assumption about the location of code somewhere, I assume? I've been building the tests in my environments but it takes a long time, since I only have the Pi, and an emulated Linux environment. Both are quite slow.

**Comment by uweseimet** [comment]
@rdmark I am going to investigate now what's happening on my machine. Can you please wait with merging until I know more details? It might be required to change something in the offending test.

**Comment by uweseimet** [comment]
@rdmark Very strange: When running the tests in my regular enviroment (last time I was using a different folder with a fresh checkout) everything is passing. The tests do no require any special setup, and I have no idea what caused them to fail.
Anyway, things appear to be fine now.

**Review by uweseimet — APPROVED** [review]

**Comment by uweseimet** [comment]
@rdmark Do the tests in RASCS/test/robot still have any relevance?

**Comment by rdmark** [comment]
> @rdmark Do the tests in RASCS/test/robot still have any relevance?

@uweseimet I believe these are the hardware tests that run in @akuker's personal lab environment

**Comment by uweseimet** [comment]
@rdmark We might address this in a separate step, depending on @akuker's feedback. I would appreciate the current changes to be merged soon, because otherwise it's inconvenient for me to continue with issue 663, which I need to update based on the changes of this PR.

**Comment by rdmark** [comment]
@uweseimet Agreed, there is no rush to clean this up in this PR. All the unit tests passed also on my RPi3+ w/ Bullseye so this is good to go.

**Pull request merged**
