### PR TITLE
Code cleanup, especially casts, lambdas, data types, encapsulation

### PR DESCRIPTION
**Pull request by uweseimet**
Some cleanup stuff, mostly based on C++ best practices:

- Use more static casts (recommended for C++)
- Lambda syntax cleanup, in particular in the unit tests
- Improved encapsulation of the controllers
- Replaced pointers by references
- Removed all remaining occurrences of the legacy DWORD and BYTE types, making os.h obsolete

Note that the bugs, security issues and code smells reported are not new code. They have been there before and are part of the bad code in cfilesystem.cpp.

### CODE REVIEW

**Comment by rdmark** [comment]
@uweseimet Please note that branches with the "feature_" naming scheme are treated as long-lived branches in SonarCloud now. If you intended feature_minor_code_cleanup to be long-lived then that's fair game of course!

**Comment by uweseimet** [comment]
@rdmark I thought this was only for branches starting with "release-" or "feature-", i.e. with a hyphen and not an underline character. But you are right, I missed that, and it is not intentional that my branches are long-lived branches.
Can you please delete my feature branches except for feature_minor_code_cleanup? That one can be deleted later, when the respective PR has been merged.

Branch names starting with "feature-" are not long-lived, are they?

**Comment by rdmark** [comment]
@uweseimet Correct, branches that begin with "feature-" aren't treated as long-lived. But perhaps they should?
```
Long-lived branches pattern: (develop|feature_.*)
```
In my mind, long lived branches are those that make broad changes or implement a large chunk of new code, and will be iterated on over multiple weeks or longer. Hence, the need for continuous and persistent code quality scanning on them.

What do you think is a good branch naming scheme, that covers the various types of development that happen in this project?

**Comment by uweseimet** [comment]
@rdmark IMO for rascsi it is sufficient that only develop (besides master) is a long lived branch. For much more than a year (if I remember correctly) there has never been any feature branch that was alive for several weeks. Except for the branches marked as stale in github. I doubt that most of those are still useful. They have not been maintained/changed for ages, and it is unlikely that they can ever be merged into the current codebase after such a long time.
As far as I can tell I was not that wrong with my previous assumption: By default "branch-" and "release-" appear to be the standard default branches.

**Review by akuker — APPROVED** [review]

**Comment by akuker** [comment]
Good to go! Thanks @uweseimet !

**Comment by uweseimet** [comment]
@akuker Thank you for reviewing!

**Pull request merged**
