### PR TITLE
rasdump and monitor updates, made rasdump work, improved bus abstraction

### PR DESCRIPTION
**Pull request by uweseimet**
@akuker This PR makes rasdump work, based on the old bus code. I added a gpiobus factory like yours, which currently only returns a Raspberry Pi bus, and additionally initializes it so that the clients do not have to do this.
Re-adding your changes for the Banana Pi is a matter of 10 minutes. Essentially you just have to replace the files in the hal folder by the new code, and you have to ensure that the factory initializes the bus, i.e. calls bus->Init() and bus->Reset() because the clients don't need to do that mandatory work anymore.

Except for rasdump there are not that many changes, most of the changes are the replaced files in the hal folder.

From that perspective I think it makes sense to temporarily revert your Banana Pi changes. What you get in return is a working and improved rasdump, an better bus abstraction, SonarCloud analysis for rasdump and scsimon, and a lot of cleaned up and de-duplicated code. Sounds like a good deal to me ;-).

### CODE REVIEW

**Comment by uweseimet** [comment]
@rdmark In case @akuker agrees to proceed as I suggested it may be useful if the web UI supported creating drive images of real devices by calling the rasdump tool. As rasdump cannot run when rascsi is already running (and vice versa) rascsi would have to be shut down first.
In the ideal case rasdump would offer a protobuf remote interface, and would support scanning for connected devices. The UI could then display a list of available devices to dump.
What's your opinion on that?

**Comment by rdmark** [comment]
@uweseimet When you say rascsi would have to relinquish bus control, would that mean that the process has to be terminated and then started up again after rasdump is finished? Or do you have some other mechanism in mind, in case we don't go down the road of integrating rasdump into rascsi?

The one argument I could think of not to integrate rasdump into rascsi would be the Unix philosophy or small, modular programs that work in unison. Rascsi already has a huge amount of functionality built into it and is quite a memory intensive program. This is just my 2 cents however.

Regardless, having a user friendly front end for dumping physical hard disk images and immediately making them available to the user as image files sounds like a very powerful and handy feature, indeed. I would be up for trying to make that work in the Web Interface.

**Comment by uweseimet** [comment]
@rdmark Regarding relinquishing bus control: If there are two different processes only one can use the bus, the other has to relinquish it.
I agree with what you say about the Unix philosophy, but a process that listens on sockets is not a regular Unix tool that does something when being started and then pipes the output to the next tool and so on. We are dealing with server processes here. Having two separate processes is a much bigger effort and requires more hardware resources than having just one, and you would have to duplicate a lot of functionality, like dealing with the network and with protobuf messages. This is comparable to what you have with web servers: There are not several of them on the same machine just because you have several websites/domains. There is a single server instead with multiple virtual hosts.

But instead of adding new tickets with features like that it might be better to first clean up/resolve the existing ones. Or to reject them, because they are not realistic. There are roughly these categories of existing backend tickets:

- Adding additional SCSI  commands: This is the minority because at least for the existing device types there is not that much that can be added. As big as it is, the SCSI standard has a limited scope.
- Completely new features: Tickets like tape drive support, SCSI/USB bridge, BIN/CUE support, action hooks etc. require man weeks or even man months. Tickets of that kind should not be accepted unless the author is also going to implement them. Who else than the author is going to work on those, considering that a lot of expert knowledge (SCSI, Samplers, other protocols, Linux kernel potentially) is required? As far as I can tell since this project started it has essentially been a backend one-man-show, and for some of these tickets you even need SCSI hardware you can verify against, e.g. a streamer.
- Features just one or two users are interested in. The X68000 stuff in particular, which is broken beyond repair. Who is going to maintain this code nightmare, which has more SonarCloud issues than it has lines of code? Who is going to add unit tests? This code should be discarded, because just like the SASI controller it binds resources and potentially blocks further development of other features much more than just two users might profit from.
- Tickets dealing with low-level protocol issues like https://github.com/akuker/RASCSI/issues/656. These are tricky and might require signal analyzer hardware. Also see https://github.com/akuker/RASCSI/issues/656#issuecomment-1302466190.
- Code improvements: Not that much left to do IMO when you do not take the X68000 stuff and scsimon into account. About 70-80% of the non-X68000 code are essentially new by now, and this new code is covered with unit tests very well.

Just my two cents.

**Review by akuker — APPROVED** [review]

**Comment by akuker** [comment]
> @rdmark In case @akuker agrees to proceed as I suggested it may be useful if the web UI supports creating drive images of real devices by calling the rasdump tool. 

@uweseimet  - in my opinion, I don't think we need to easily switch back and forth between `rascsi` mode and `rasdump` mode. IMHO, these are completely different use cases and most likely involve switching cables around (and we ALWAYS shut down our hardware before switching SCSI cables, right? ;-) )

> Even better: rasdump should be integrated into rascsi. If rascsi receives a command that requires to switch from target to initiator mode, it can just do that, and later switch back. All in all that is a major effort, but definitely less than adding a protobuf interface to rasdump and figuring out how to avoid conflicts between rascsi and rasdump, and starting/stopping either the one or the other. rascsi also knows the image folder, i.e. it knows where dumped images should be stored. Integrating rasdump into rascsi without adding any remote functionality would be the first step towards this goal.

This scares me. I would have no objection to updating the web interface to be able to control rasdump. But IMHO, it should stop RASCSI, then run rasdump. Maybe a completely different `tab` or some way to differentiate that this is completely different functionality from normal rascsi operation.

Creating a wiki page with detailed instructions, screenshots and troubleshooting tips would accomplish about the same goal (IMHO).

**Comment by uweseimet** [comment]
@akuker The problem with the cables is a very good point, which I did not think of yet ;-). Let's just forget the whole thing. From a software perspective this would have been interesting, but it causes too many practical issues.

**Pull request merged**
