### PR TITLE
Fix the file upload functionality

### PR DESCRIPTION
**Pull request by rdmark**
- Move to a standard file upload solution using save() -- should fix both issues described in https://github.com/akuker/RASCSI/issues/228
- Add file type validation and help text for file picker -- fixing https://github.com/akuker/RASCSI/issues/61

### CODE REVIEW

**Comment by rdmark** [comment]
Testing this compared to the previous solution, a 550-650 MB file upload takes about twice as long to upload as with the previous (around 2min 30s, compared to 1min 10s before). Not sure if this is acceptable...

**Comment by rdmark** [comment]
@erichelgeson I found something that seems to be a pretty solid solution:  dropzone and pydrop.  Pushed the code here.  Performance wise, it is slightly slower than the status quo, at 1min 30s for my canonical 600MB file.  However, in addition to not corrupting files, it's a much more user friendly solution.  You can line up several files for upload in parallel, see the progress in real time, cancel transfers in progress, etc.  It has solid error handling, as well as instantly catching too large files and duplicated names.

The only TODO here is that the layout is a bit borked in our template. Should be easily fixable.

**Comment by rdmark** [comment]
@erichelgeson This is ready for review.  In my tests, it takes just over 5min to transfer a 2GB file, compared to 3.5m with scp. I could not test this large a file size with the old solution, as it kept timing out.

**Comment by rdmark** [comment]
I messed this PR up a bit by changing the target branch to develop.  Will rebase once https://github.com/akuker/RASCSI/pull/246 gets merged.

**Review by erichelgeson — APPROVED** [review]

**Pull request merged**
