### PR TITLE
Tentative Web UI for the Printer device.

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Review by uweseimet — CHANGES_REQUESTED** [review]
0 is not a valid timeout value. The printer devices expects the timeout to be positive, otherwise it reports an error.

**Comment by uweseimet** [comment]
@rdmark Indeed, I missed adding the parameters. They are now present (in the current feature branch).
Note that the ATTACH information is more of a general kind, but any client with dynamich parameter handling has to use the meta data for the respective device, where the new parameters have already been exposed.

```
...
  SCDP  Supported LUN numbers: 0-31
        Parameter support
        Default parameters: interfaces=eth0
  SCHS  Supported LUN numbers: 0-31
  SCLP  Supported LUN numbers: 0-31
        Parameter support
        Default parameters: cmd=lp -oraw %f:timeout=30
```

**Comment by rdmark** [comment]
@bzeiss For your attention, I'm proposing a small change to RaCtlCmds.attach_image():

- Rename to attach_device()
- Instead of hard coded known parameters, it now takes a dict _params_ in which the keys are parameter names such as file, interfaces, cmd, and timeout, while the values are values of those parameters.

The benefit of doing this is that a client can now pass any arbitrary parameter to the protobuf interface, which makes it easy to adapt when new capabilities are added to the rascsi backend. Please let me know what you think!

**Comment by uweseimet** [comment]
@rdmark When reading your latest comment I'm not sure whether you are going to add (or cannot because of framework limitations) dynamic parameter support.
Note that in your current sources the setting for "cmd" is not a valid one (anymore), because the mandatory filename placeholder is missing. In case of getting the default parameters from rascsi you would not have to bother with this.

**Comment by bzeiss** [comment]
@rdmark yes, sounds like a good idea given that the list of things you attach to a scsi id isn't always a disk image. I like the idea.

**Comment by rdmark** [comment]
@uweseimet Yes, I'm addressing this one step at a time. :)

The first step, to make the underlying interface more flexible, has now been addressed.
Right now I'm looking into how to use Flask's [request.form ](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Request.form) data structure dynamically, so that the web app doesn't have to know ahead of time the number of and names for form elements.

**Comment by uweseimet** [comment]
@rdmark Sounds good! Since the web ui is part of each RaSCSI release dynamic parameter handling is useful, but not as import as it is for my app. The app can be connected to any RaSCSI version, so the only way to suggest valid parameters is to always get the respective information from rascsi.

**Comment by rdmark** [comment]
@uweseimet I was thinking: What do you say about having the server report default_parameters for network interfaces as ``` interfaces=X:ip=Y:mask=Z ```? With this, I could standardize the Web UI for this kind of device, too.

**Comment by uweseimet** [comment]
@rdmark Yes, "interfaces=X:ip=Y:mask=Z" may be better. Currently this is "interfaces=X:Y:Z", isn't it? We can keep the old syntax for some time, but should remove it later in favor of the new syntax. 
I will create a ticket for this change.

**Review by uweseimet — APPROVED** [review]

**Pull request merged**
