### PR TITLE
SCSI command dispatcher update, reduction of circular dependencies

### PR DESCRIPTION
**Pull request by uweseimet**
These changes make the SCSI command dispatching more consistent (before some commands were logged, others were not), and hopefully also more readable. As far as I can tell (haven't coded in C++ for a long time) there was also a potential issue with cast the command to an enum for the switch. If the command byte is not a valid enum value depending on the C++ level the result may be undefined.
With these changes it may be possible to later replace the switches by a more object-oriented approach.

I also moved enum definitions to the base class in order to reduce circular dependencies.

I'm concerned about sasidev_ctrl refering to SCSIDaynaPort. The code for the different devices should not have hard-coded dependencies. My guess is that the current code is already hard to test because hardly any user has all these often exotic computers. Currently, a change somewhere can lead to numerous side effects.

@akuker I would like to hear your opinion on the changes and comments above.

### CODE REVIEW

**Comment by akuker** [comment]
I like where your head is. I agree that there shouldn't be anything daynaport in the SASI/scsi classes. It looks like you're doing some awesome stuff to work towards cleaning that up. 

I was actually thinking of eventually creating callbacks for all of the commands so that they can just exist in the device-specific classes. The devices could register callbacks for whatever commands they support. That way the controller doesn't have to know anything about the device itself.

**Comment by uweseimet** [comment]
When we look at the SCSI specifications on https://www.t10.org/drafts.htm there is base functionality (SPC) and more specific functionality (SBC, MMC etc.) It may make sense to have the code reflect this in one way or the other. This would result in device type-specific classes (SBC, MMC, ...) and potentially device-specific classes on top of those (RASCSI, SEAGATE, ...).
Getting there is probably not be straightforward and may take many small steps.

Anyway, I am going to create the PR from the draft now with my latest changes, which are hopefully going into the right direction. Interestingly there was no need from scsidev_ctrl to inherit from sasidev_ctrl.

**Comment by uweseimet** [comment]
@akuker While waiting for your review I replaced the SCSI command dispatcher in order to get rid of one of the big switches in the code.

**Comment by akuker** [comment]
FYI: I ran the regression "Robot" tests and everything passed. Thank you for the awesome pull request!!

**Review by akuker — APPROVED** [review]

**Pull request merged**
